natsStreaming:
  host: localhost
  port: 4222
  clusterId: test-cluster
  publisherId: pub
  consumerId: cons
  subject: orders
  durableName: my-durable

database:
  host: localhost
  port: 5432
  user: docker
  password: docker
  name: orders